# Generated by Django 2.0.6 on 2018-11-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='latest_posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('content', models.CharField(max_length=2451)),
            ],
        ),
    ]
